- notifications_utils/clients/statsd/statsd_client.py
- notifications_utils/logging.py
- notifications_utils/recipients.py
- notifications_utils/version.py
- tests/test_logging.py
- tests/test_recipient_validation.py
We need to log stdout only in production
> Removed file writing from prod logging

- notifications_utils/timezones.py
- notifications_utils/version.py
- tests/test_timezones.py
Part of https://github.com/cds-snc/notification-api/issues/118. 
Essentially introduces two new functions that can be used instead of hardcoding EST.
> Conf timezone

- notifications_utils/jinja_templates/email_template.jinja2
This PR move the Canada WordMark to the bottom of the email branding.
I also clean up the markup.
> Move fip images

- notifications_utils/jinja_templates/email_preview_template.jinja2
- notifications_utils/version.py
- tests/test_template_types.py
This to support translating strings in https://github.com/cds-snc/notification-admin/pull/259
> Added square brackets, bumped patch version

- notifications_utils/jinja_templates/email_template.jinja2
- notifications_utils/version.py
https://github.com/cds-snc/notification-api/issues/398
> Add no branding option

- notifications_utils/jinja_templates/email_template.jinja2
- notifications_utils/version.py
Make sure custom logos are aligned properly too
> Fix alignment of custom branding logos

- notifications_utils/field.py
- notifications_utils/version.py
Closes https://github.com/cds-snc/notification-api/issues/983
> Add french values that convert to "true"

- notifications_utils/__init__.py
- notifications_utils/version.py
- tests/test_recipient_validation.py
Related to https://github.com/cds-snc/notification-api/issues/760
> Validate email addresses with special characters

- notifications_utils/formatters.py
- notifications_utils/version.py
- tests/test_formatters.py
Fixes https://github.com/cds-snc/notification-api/issues/1139
Only fixed the space before pipe issue, there are some rules @anikbrazeau or @bryan-robitaille could review later https://github.com/cds-snc/notification-api/issues/1139#issuecomment-696139452
👉  I'll tag a release after merging this PR + bump utils on admin/api after
> Whitespace before a pipe is fine

- notifications_utils/version.py
- setup.py
Doing this first and then I'll bump utils on admin and API
> Upgrade Python dependencies

- notifications_utils/version.py
- setup.py
These need to be updated to solve the downstream issues we're seeing on Admin. Tested locally and this doesn't seem to break anything.. I'll put up an admin app as soon as this is merged.
> Bump some dependencies to avoid pip issues

- notifications_utils/strftime_codes.py
- notifications_utils/template.py
- notifications_utils/version.py
- tests/test_strftime_codes.py
Improved platform compatibility by offering a set of `strftime` format codes for both POSIX-like environment and Windows platforms.
So far, the build will tell us if everything is fine. I should add unit-tests ideally. 
This is a suggested checklist of questions reviewers might ask during their review | Voici une suggestion de liste de vérification comprenant des questions que les réviseurs pourraient poser pendant leur examen :
> Improved platform compatibility (windows)

- notifications_utils/strftime_codes.py
Very small change: added missing typings in strftime_codes
This is a suggested checklist of questions reviewers might ask during their review | Voici une suggestion de liste de vérification comprenant des questions que les réviseurs pourraient poser pendant leur examen :
> Added missing typings in strftime_codes

- notifications_utils/clients/redis/__init__.py
- notifications_utils/version.py
See https://github.com/cds-snc/notification-api/pull/1268#issuecomment-822404184
Will merge, tag a new release and use the new version on the API just after
> Add Redis keys when near or over the daily limit

- notifications_utils/__init__.py
- notifications_utils/base64_uuid.py
- notifications_utils/clients/antivirus/antivirus_client.py
- notifications_utils/clients/redis/redis_client.py
- notifications_utils/clients/statsd/statsd_client.py
- notifications_utils/clients/zendesk/zendesk_client.py
- notifications_utils/columns.py
- notifications_utils/field.py
- notifications_utils/formatters.py
- notifications_utils/international_billing_rates.py
- notifications_utils/letter_timings.py
- notifications_utils/logging.py
- notifications_utils/pdf.py
- notifications_utils/recipients.py
- notifications_utils/request_helper.py
- notifications_utils/s3.py
- notifications_utils/sanitise_text.py
- notifications_utils/statsd_decorators.py
- notifications_utils/strftime_codes.py
- notifications_utils/take.py
- notifications_utils/template.py
- notifications_utils/template_change.py
- notifications_utils/url_safe_token.py
- pyproject.toml
When I introduced Black in #88 , I copied the config file (pyproject.toml) from notifications-api. I failed to notice that the included directories needed to change, so Black did not actually run on the main directory here, `./notifications_utils`. 
I have now fixed that and run Black on that directory.
> Fix black config

- notifications_utils/formatters.py
- notifications_utils/template.py
- notifications_utils/version.py
- requirements_for_test.txt
- tests/test_formatters.py
- tests/test_template.py
Preliminary work on a custom hardcoded tag to include the _certified Global Affairs stamp_. I copied what @smcmurtry did with the English/French tags and replicated the logic. 
No test yet but that should come soon if we want to go forward with this.
[The image was manually uploaded into the production assets S3 bucket](https://assets.notification.canada.ca/gc-ga-seal.png) and is hardcoded into the code.
* Start local instance.
* Write a new email template.
* Include the [[ga-seal]] logo into the message.
* Send yourself a notification with it.
Shortcoming: does note appear in *preview*. I don't think at this point we want to support this too much, unless we decide to make it a feature in the future.
This is a suggested checklist of questions reviewers might ask during their
review | …
> Started work on custom hardcoded tag for Global Affairs

- .github/actions/waffles/entrypoint.sh
Fixed location of the waffle python script in docker entry point.
> Fixed location of the waffle python script in docker entry point

- requirements_for_test.txt
- setup.py
Pin transitive dependency werkzeug to 2.0.2 to align with admin and api
> Pin werkzeug to 2.0.2

- notifications_utils/version.py
Bumping up version to 48.0.0 after merge of recent dependency bump that upgraded Flask to v2.0.3.
> Sequential steps (1., 2., 3., ...) that describe how to test this change. This
> will help a developer test things out without too much detective work. Also,
> include any environmental setup steps that aren't in the normal README steps
> and/or any time-based elements that this requires.
---
> Étapes consécutives (1., 2., 3., …) qui décrivent la façon de tester la
> modification. Elles aideront les développeurs à faire des tests sans avoir à
> jouer au détective. Veuillez aussi inclure toutes les étapes de configuration
> de l’environnement qui ne font pas partie des étapes normales dans le fichier
> README et tout élément temporel requis.
> Release 48.0.0

- .github/actions/waffles/waffles.py
Print failures from waffles validation
> Print Waffles failures

- notifications_utils/version.py
- pyproject.toml
Bumping the Utils version in pyproject.toml
> Bump utils version

- Makefile
- notifications_utils/clients/redis/bounce_rate.py
- tests/test_bounce_rate.py
Add functions for bounce rates in utils so it can be used across admin and api
> Add functions for bounce rates

- pyproject.toml
> Update notification to 50.1.6

- .github/actions/waffles/requirements.txt
- pyproject.toml
Updating waffles action touse  50.1.6
> Updating waffles for new version of utils 50.1.6

- pyproject.toml
> need a new patch version 50.1.7

- .github/actions/waffles/requirements.txt
- pyproject.toml
Merged all the renovate PRs. This will be the new tagged version with all the renovate changes to different packages.
> Update notification utils to 50.1.8

- notifications_utils/clients/redis/bounce_rate.py
- notifications_utils/clients/redis/redis_client.py
- tests/test_bounce_rate.py
- tests/test_redis_client.py
This PR will allow us to change how seeded data works. Instead of having a different data structure in Redis for seeded data, we can just do a bulk insert of the seeded data into the same data structure we use normally.
> Change how seeded data works

- .github/actions/waffles/requirements.txt
> Update waffles to use latest utils version

- tests/test_bounce_rate.py
Not strictly necessary but I thought there might have been a bug here so I re-wrote the test.
> Improve the tests for `get_bounce_rate`

- .github/actions/waffles/requirements.txt
- notifications_utils/clients/redis/bounce_rate.py
- pyproject.toml
- tests/test_bounce_rate.py
Added notification id as an arg to `set_sliding_notifications` and `set_sliding_hard_bounce`, updated tests
Tests should pass in CI.
> Add `notification_id` as an arg to `set_sliding_notifications` and `set_sliding_hard_bounce`

- notifications_utils/url_safe_token.py
As a followup to #204 , add typing and documentation to the token code.
> improve typing and documentation in token code

- notifications_utils/clients/redis/__init__.py
Add email daily count cache key
> Add email daily count cache key

- .github/actions/waffles/requirements.txt
> Update utils version in waffles

- .github/actions/waffles/requirements.txt
- pyproject.toml
Forgot to bump waffles before tagging.
> Bump version with waffles bump as well

- .github/actions/waffles/requirements.txt
- pyproject.toml
Upgrade Flask for waffles, bump utils version.
> Bump the Flask version for waffles

- notifications_utils/clients/redis/__init__.py
New cache keys for email daily limits
> New cache keys for email daily limit

- .github/actions/waffles/requirements.txt
- pyproject.toml
> New tag 52.0.4

- .github/actions/waffles/requirements.txt
> Bump waffles version

- .github/actions/waffles/requirements.txt
> update waffles to 52.0.10

- .github/actions/waffles/requirements.txt
- notifications_utils/logging.py
- pyproject.toml
- tests/test_logging.py
Replace the signed secret in the api log message
> Replace a signed secret in the api log message

- poetry.lock
- pyproject.toml
Update boto3 and awscli. The last time we did this update we ran into a bunch of issues on trying to login on api/ admin. 
Testing:
- used this branch on api/ admin and saw no issues in the logs or the frontend.
https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1425
> Update boto and awscli

- .devcontainer/Dockerfile
- .github/actions/waffles/requirements.txt
- .github/workflows/ci.yaml
- docker/Dockerfile
- poetry.lock
- pyproject.toml
upgrade poetry and cryptgraphy (see [here](https://github.com/cds-snc/notification-utils/security/dependabot/31)) to latest.
> upgrade poetry and cryptography
