notifications_utils/recipients.py, notifications_utils/version.py, requirements_for_test.txt, tests/test_recipient_csv.py, tests/test_recipient_validation.py
You can now dynamically set the phone region using `PHONE_COUNTRY_CODE` and `PHONE_REGION_CODE` env variables. Defaults are `1` and `US` respectively.
It uses `phonenumbers` to extrapolate if a phone number is local or international vs hardcoded logic.
=> International

notifications_utils/template.py, notifications_utils/version.py
This allows the admin and API repos to use local jinja when testing, to avoid having to push changes through this repo before knowing if they are correct.
Part of: https://github.com/cds-snc/notification-api/issues/759
=> Add support for 'local' jinja filepaths

notifications_utils/jinja_templates/email_template.jinja2, notifications_utils/template.py, notifications_utils/version.py, tests/test_template_types.py
This PR is in tandem with other PR's in notification-admin and notification-api.
This addresses the first 2 bullet points of https://github.com/cds-snc/notification-api/issues/761
Cleans up variable names, and makes it more clear how the radio buttons in the admin interface correspond to what the code does.
=> Make branding variable names easier to understand

notifications_utils/jinja_templates/sms_preview_template.jinja2
I tested this with `USE_LOCAL_JINJA_TEMPLATES` in notification-admin (thanks @brdunfield !). Translations are appearing correctly:
Note: "phone number" is not coming from the template so that will have to be fixed in notification-admin.
=> Added [] to sms preview template so we can translate it in the admin

notifications_utils/jinja_templates/sms_preview_template.jinja2
Moved the colons inside the brackets so we can add a space before the colon for french:
=> SMS preview template FR fix

notifications_utils/jinja_templates/email_template.jinja2, notifications_utils/template.py, notifications_utils/version.py, tests/test_template_types.py
Removes the check for a specific custom brand name, and adds a fip_banner_french variable check instead. This new variable will come from the admin / api (PRs going up shortly).
This PR will need to be merged to verify tests on the other two.
=> French FIP Support

notifications_utils/jinja_templates/email_template.jinja2, notifications_utils/version.py
When we next upgrade prod from staging, services currently using the french-fip hack will break until we manually migrate them to the new branding. This PR will stop this from happening, and retains the existing hack. Once prod has been migrated, we can remove the hack fully from the code.
=> Restore old french fip branding for migration purposes

notifications_utils/logging.py, notifications_utils/version.py
This PR is to fix the following Sentry error: https://sentry.io/organizations/canadian-digital-service/issues/1661335514/?project=1522963
This happened whenever a dict was sent to the logger:
https://github.com/cds-snc/notification-api/blob/675880e93b469464d4c7cc35eb84afa9793d1024/app/user/rest.py#L228
and
https://github.com/cds-snc/notification-api/blob/master/app/errors.py#L80
Not 100% sure how to test this before merging.
=> Fix logging

notifications_utils/jinja_templates/email_template.jinja2, notifications_utils/version.py, tests/test_template_types.py
Jinja CSS changes to close: https://github.com/cds-snc/notification-api/issues/863
Emails should be centred on larger screens, and aligned with the Branding logo.
On smaller screens, there should be adequate padding on either side of the content.
Can be tested by running admin and api locally, setting USE_LOCAL_JINJA_TEMPLATES=True in api, and copying email_template.jinja2 into the api folder as directed in the readme. Send emails using the default fip and see how they display.
=> CSS changes for FIP emails

notifications_utils/recipients.py, notifications_utils/version.py, tests/test_recipient_csv.py
Still default to a max of 50k rows for CSVs, but allow it to be set in the admin or api. This is part of https://github.com/cds-snc/notification-api/issues/860 and groundwork for https://github.com/cds-snc/notification-admin/pull/550.
=> Allow max rows to be set from the outside

notifications_utils/field.py, notifications_utils/template.py, notifications_utils/version.py, tests/test_field.py, tests/test_template_types.py
Related to https://github.com/cds-snc/notification-api/issues/850
It's possible to translate things in Jinja templates by adding brackets. This PR adds the possibility to translate placeholders.
The idea is to add brackets so that they'll be translated at the rendering phase.
=> Support translation of template fields

notifications_utils/formatters.py, notifications_utils/version.py, tests/test_formatters.py
Follow up of https://github.com/cds-snc/notification-utils/pull/61. Turns out it's not solved!
Turns out that another method has a bug, where pipes are cleaned where only dashes should be cleaned.
Cleaned up the regex, added a test for this method and a dedicated test for the subject field.
=> Bug: hyphens_with_en_dashes cleans up pipes

notifications_utils/clients/statsd/statsd_client.py, notifications_utils/version.py, setup.py, tests/test_statsd_client.py
We have seen recently that sending requests to StatsD may take an enormous amount of time, leading to slow responses (> 1s). Our custom StatsD client may be the culprit. With our current implementation, we reuse a single socket to send requests but we resolve DNS each time. The original client doesn't do this, but [caches the DNS response forever](https://github.com/jsocol/pystatsd/blob/f3f304b4b2c3d5eddeb9f4977d9c82c64c37a052/statsd/client/udp.py#L34-L44). This is not appropriate for us as this pod could have its IP changed by Kubernetes as it rearranges pods.
My assumption is that sometimes DNS requests can take a larger amount of time. It's also unreasonable to resolve DNS constantly, this may lead to network congestion or overload the k8s DNS server.
GDS had performance issues using …
=> Cache DNS requests for StatsD host

notifications_utils/jinja_templates/email_preview_template.jinja2, notifications_utils/jinja_templates/sms_preview_template.jinja2, notifications_utils/version.py, tests/test_template_types.py
The admin pulls from these files to show the previews. These ones are okay to modify / tailwind-ify here as they are *only* used in the admin previews. Note that for actual email styling we will not be able to do this.
There will be an associated PR going up for admin as well
=> Update preview template styles

notifications_utils/jinja_templates/email_template.jinja2, notifications_utils/version.py, tests/test_template_types.py
Link images sent in emails on assets.notification.canada.ca instead of using an S3 URL.
Note that emails that have already been sent will use the old URLs and images will still load. Logos have already been migrated to the appropriate S3 bucket
Similar work than on https://github.com/cds-snc/notification-admin/pull/823
=> Store email assets on canada.ca

notifications_utils/version.py, scripts/bootstrap.sh, setup.py
The `pip` tool changed its internal resolver for dependency resolution. The dependency management is stricter and some of our dependencies were found to be in conflict. To know more about these changes, [head over to this blog post](https://pyfound.blogspot.com/2020/11/pip-20-3-new-resolver.html).
For the *notification-utils* project, I simply upgraded the `boto` dependency and made sure it is aligned with the *notification-admin* project.
I've cleaned my local virtual environments a few times, used the `--no-cache-dir` of `pip install` as much as I could and reinstall these changes couple of times, referring to my local *notification-utils* project from the *notification-admin* project.
=> fix: resolved dependency hell with latest pip resolver upgrade

notifications_utils/statsd_decorators.py, notifications_utils/version.py, tests/conftest.py, tests/test_statsd_decorators.py
https://trello.com/c/62gscLJH/169-graph-the-services-going-over-the-daily-rate-limit
For improving our coverage of statsd metric, a `statsd_catch` annotation will increment a counter based on given namespace and counter name **when** the defined exception is raised
This will immediately be useful to send statsd metrics with the daily rate limit.
* Mostly unit tests in the context of the *notification-utils* project.
=> Added a statsd_catch annotation to count thrown exceptions

notifications_utils/version.py, setup.py
Updating project dependencies.
PyYAML cannot go to the newest version right now though since the awscli 1.19.0 depends on PyYAML<5.4 and >=3.10
=> Update utils dependencies

notifications_utils/clients/statsd/statsd_client.py, notifications_utils/version.py
Those were confusing, the first argument should be in the future but it was named `start`. Renaming variables.
=> Reverse arguments for timing_with_dates

notifications_utils/logging.py, notifications_utils/version.py, tests/test_logging.py
We want to be able to have metrics for HTTP endpoints when requests are successful and we have a `service_id`. At the moment we have only timers/counters per service but we something without a service ID is needed if we want to use stats for some endpoints.
We need this to compute SLOs for example, we are interested in stats for specific endpoints
```
POST /v2/notifications/email (sending an email)
POST /v2/notifications/sms (sending an SMS)
GET /v2/notifications (getting the status of a notification)
```
There were no tests covering recording stats so I've added one.
=> Record StatsD stats with and without service IDs

notifications_utils/jinja_templates/email_template.jinja2, notifications_utils/version.py
We got reports that list items were cut off on Outlook. Seems to [be common](https://uplandsoftware.com/postup/resources/blog/solutions-for-bullet-points-that-shrink-or-disappear-in-outlook/).
Implemented some recommended HTML fixes found here:
- https://litmus.com/community/discussions/1093-bulletproof-lists-using-ul-and-li
- https://stackoverflow.com/questions/57142744/html-tags-ul-li-not-working-in-windows-outlook
Tested this by sending an email to myself using the AWS Console and looking at it on Gmail + on Outlook Office 365. Checked before that the bug was present on Outlook Office 365 as well.
=> feat: better list item style for Outlook

notifications_utils/version.py
I did not upgrade the version in https://github.com/cds-snc/notification-utils/pull/79, or in fact I kept the old version but merged #80 before. Sorry about that.
=> Bump version to 43.8.0

notifications_utils/formatters.py, notifications_utils/logging.py, notifications_utils/version.py, tests/test_formatters.py, tests/test_logging.py
Add bold, italic and h2 header to email templates.
Looked at how Veteran Affairs did it in the US
- https://github.com/department-of-veterans-affairs/notification-utils/commit/fc4e518ab2e86dbd36dc5cc8f11b638746d83e11
- https://github.com/department-of-veterans-affairs/notification-utils/commit/38700405b2c56e2d680b54b30dc3e4f6d091da17
TODO: pull it this new version on admin and API. ⚠️ does not have a CSS rule for `<strong>` yet
=> feat: add bold, italic and h2 header

notifications_utils/formatters.py, notifications_utils/version.py, tests/test_formatters.py
At the moment, using `**` at the beginning of the list does not work as intended, it tries to create multiple list items.
```
_italic_ and **bold**
**Title**: test
```
renders like
This is because we have a custom regex, allowing lists to not have a space after an initial `*`. The original library does not have that (it's not standard Markdown)
https://github.com/lepture/mistune/blob/6470c42b2087a4649ad0437227cf7b5c570c3a91/mistune.py#L121, the relevant part is ` [\s\S]+?` (space before `[\s\S]+?`)
Tweaked the regex to make sure we don't match `**` as the start of a list. There are no regressions for other list tests in `test_formatters.py`
Trello: https://trello.com/c/22a6eKqK/513-fix-confusion-between-bold-and-lists
=> fix: avoid confusion between list and bold

notifications_utils/jinja_templates/email_preview_template.jinja2, notifications_utils/template.py, notifications_utils/version.py, tests/test_template_types.py
Show logos in email previews on the admin.
Supports:
- FIP EN
- FIP FR
- custom logo with URL
- custom logo with URL and text
Most of the Jinja code is stolen from the [email Jinja template](https://github.com/cds-snc/notification-utils/blob/master/notifications_utils/jinja_templates/email_template.jinja2) but simplified because we don't need tables for the web.
I've reused a lot of tests to prove that things are displayed as expected.
Admin PR pulling in this change: https://github.com/cds-snc/notification-admin/pull/1026
=> Show logos in email previews

notifications_utils/formatters.py, notifications_utils/jinja_templates/email_preview_template.jinja2, notifications_utils/jinja_templates/email_template.jinja2, notifications_utils/version.py, tests/test_formatters.py, tests/test_template_types.py
A few email template changes to deal better with dark mode.
- Remove the default link colour. The colour isn't nice when it's inverted automatically in dark mode
- Add a white background to the GoC logos to make sure they are legible in dark mode
- Add a custom background when using a logo with a custom background color
- Review GoC image sizes, paddings and margins
- Update email previews to match changes done in the email template
Trello https://trello.com/c/aMaFC4rY/658-better-dark-mode-for-emails
=> feat: dark mode support for emails

notifications_utils/jinja_templates/email_preview_template.jinja2, notifications_utils/jinja_templates/email_template.jinja2, setup.cfg, tests/test_template_types.py
~I will convert from draft after I fix the tests.~ Fixed
I noticed that there was no alt text for the Canada wordmark inserted at the bottom of Notify emails, so screen readers read nothing for this. I looked at Canada.ca and copied the english and french alt text from there:
=> Added alt text to the Canada Wordmark

mypy.ini, notifications_utils/clients/redis/redis_client.py, notifications_utils/clients/statsd/statsd_client.py, notifications_utils/field.py, notifications_utils/logging.py, notifications_utils/recipients.py, notifications_utils/request_helper.py, notifications_utils/statsd_decorators.py, tests/test_statsd_client.py, tests/test_statsd_decorators.py, tests/test_template_types.py
Adding `check_untyped_defs = True` to the mypy config file tells mypy check inside functions without type definitions (https://mypy.readthedocs.io/en/stable/config_file.html#confval-check_untyped_defs). This helps catch more errors. I'm starting with this repo since it is smaller and less of a lift to fix/ignore the existing errors.
=> MyPy "check untyped definitions"

notifications_utils/version.py
Bumping version from 44.0.0 to 44.1.0
Added a couple of functions which were merged but I forgot to bump up the version to create a release
=> Bump version from 44.0.0 to 44.1.0

notifications_utils/field.py, scripts/run_tests.sh, setup.py, tests/test_field.py
This will make the mypy check part of CI. I had forgotten to do that before and was just running mypy manually.
I also added some type definitions and ran black on a file we had missed previously.
=> Adding MyPy check to run_tests.sh

notifications_utils/field.py, tests/test_field.py
Trello: https://trello.com/c/ThRFxXRY/649-having-extra-parenthesis-in-a-condition-variable-make-the-latter-fail-in-templates
So far I have:
- improved a type definition (unrelated to the bug but I couldn't help myself)
- made a change to the regex that fixes the bug by putting it in a 'if' statement.
- Added tests
=> Fix template brackets bug

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, notifications_utils/logging.py, notifications_utils/version.py, tests/test_logging.py
Add a `get_class_attrs` logging method that can be used to get a
dict of a Class attribute name/value pairs.  This will replace 
the current [Config.get_config class method](https://github.com/cds-snc/notification-api/blob/e39d2ac3b4dc1a758dc2093cbdff142a07ef2c26/app/config.py#L482-L490).
This will be used to dump the Config class values when Notify
services start to validate they are configured as expected.
This PR also adds a VS Code devcontainer for local development.
* cds-snc/notification-planning#522
=> feat: get class attribute name/values 

.github/actions/waffles/requirements.txt
Pin the markupsafe package since the `soft_unicode` has been removed
which was causing all CI action runs to fail with an import error:
```python
ImportError: cannot import name 'soft_unicode' from 'markupsafe'
```
=> fix: GitHub waffles action by pinning markupsafe

.github/workflows/generate-sbom.yml
Add GitHub workflows to generate SBOMs and upload them
to Dependency-Track. This will allow us to have a view of all
the dependencies used by the org and their potential
vulnerabilities.
* cds-snc/platform-sre-security-support#94
=> feat: generate Software Bill of Materials

mypy.ini, notifications_utils/statsd_decorators.py, notifications_utils/version.py, requirements_for_test.txt
- Update test deps to get the utils library in line with admin and api as part of the werkzeug upgrade.
- Configure mypy to skip directories it shouldn't look in
- Ignore type errors related to statsd
=> Update dependencies (part of werkzeug upgrade)

.github/actions/waffles/requirements.txt, .github/actions/waffles/waffles.py
This is part of [archiving document-download-frontend](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/240).
[Adding a new endpoint to document-download-api](https://github.com/cds-snc/notification-document-download-api/pull/65) also requires:
1. [Add this endpoint to the WAF allowList.](https://github.com/cds-snc/notification-terraform/pull/492)
2. Change the waffles test to support `base64_uuid` (this PR).
1. clone the [document-download-api](https://github.com/cds-snc/notification-document-download-api) and switch to [this branch]( https://github.com/cds-snc/notification-document-download-api/pull/65)
2. `pip install` the waffles requirements in a virtualenv
3. Run something similar (with your file locations) to
```
python …
```
=> support base64_uuid in urls

notifications_utils/field.py, notifications_utils/template.py, notifications_utils/version.py
For this a11y task: https://github.com/cds-snc/notification-planning/issues/580
This add some meta information about placeholders when working with templates. 
Which means we can know whether a field should behave like a boolean, or like a string (They're still all strings though). This only enhances the UX and a11y, should not change any functionality.
=> placeholder meta

.github/actions/waffles/waffles.py, notifications_utils/version.py
add support for extra routes contained in an app's config variable `EXTRA_ROUTES`
This allows us to test admin's GCA routes.
run together with https://github.com/cds-snc/notification-admin/pull/1325 to see the GCA routes listed  / tested
```
python waffles.py iron --base-url=https://staging.notification.cdssandbox.xyz --app-loc ~/Git/notification-admin --app-lib ~/.virtualenvs/notification-admin/lib/python3.9/site-packages --flask-mod application --flask-prop application
```
```
...
Hitting endpoint 'https://staging.notification.cdssandbox.xyz/users/<user_id>'... OK.
Hitting endpoint 'https://staging.notification.cdssandbox.xyz/<path:path>'... OK.
Hitting endpoint 'https://staging.notification.cdssandbox.xyz/home'... OK.
Hitting endpoint …
```
=> add support for GCA extra routes in waffles

notifications_utils/field.py, notifications_utils/version.py, tests/test_field.py
Closes https://github.com/cds-snc/notification-planning/issues/847
This PR fixes a bug in #128 where the `{"is_conditional": True}` property can be overwritten to `False` if the same variable is used multiple times in a template. The desired behaviour is that, if a variable is used in a conditional statement, we should guide the user towards setting it to a True/False value and always display the radio buttons instead of free text in the "send to one recipient" flow here: https://github.com/cds-snc/notification-admin/pull/1316
=> Fix is_conditional bug

.github/actions/waffles/waffles.py
When waffles returns valid endpoints from a flask app, we want to remove the route /<path:path>
=> Remove path:path from waffles

notifications_utils/clients/redis/__init__.py, notifications_utils/clients/redis/redis_client.py, notifications_utils/version.py, tests/test_redis_client.py
Add redis cache keys for sms daily counts.
We store the daily notify counts for a service in redis (rather than doing a database query every time!) - here I add in code to put sms counts in redis too.
Note that it's api that actually sets and uses the values, but utils manages the naming 🤷 
Also added an "increment by" function since the sms counts will go up by more than one (for sms with more than one message part)
=> Add sms count to redis

.github/actions/waffles/requirements.txt
Waffles needs to update its version of utils to run this branch
https://github.com/cds-snc/notification-api/pull/1589
=> waffles needs updated utils for api

notifications_utils/recipients.py, notifications_utils/version.py, tests/test_recipient_csv.py
bulk jobs get validated in `RecipientCSV`. Here we use the number of sms message parts in the validation of sms bulk jobs.
Used in https://github.com/cds-snc/notification-api/pull/1606
=> use number of message parts in RecipientCSV validation

README.md
Migrated the Google document on how to setup the notification-utils project into GH wiki:
https://github.com/cds-snc/notification-utils/wiki/How-to-work-with-notification-utils-locally
=> Redirect to GH wiki instead of Google doc

.devcontainer/Dockerfile, .github/actions/waffles/Dockerfile, .github/actions/waffles/requirements.txt, .github/workflows/ci.yaml, mypy.ini, notifications_utils/field.py, notifications_utils/recipients.py, notifications_utils/version.py, pyproject.toml, requirements_for_test.txt, setup.py, tests/test_recipient_csv.py
https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/959
Upgrade Python from 3.9 to 3.10
Notes:
- need to switch from the library orderedset to ordered_set since the former does not support 3.10 and is possibly abandonware.
See if this utils works with upgraded apps:
admin: https://github.com/cds-snc/notification-admin/pull/1400
api:
document-download-api:
=> Upgrade to Python 3.10

notifications_utils/logging.py, pyproject.toml, tests/test_logging.py
Currently we log the config when admin or api boots. However we redact the secrets. This makes the logging not very useful in ensuring that we're using the correct secrets 😅 
In this PR we change this so that if a secret has length >= 20 we log the last 2 digits.
Tested by using this branch on api and when booting see things like
```
'DANGEROUS_SALT': '***wm'
```
Can use this branch with api or admin to see the new behaviour on startup. Change your `pyproject.toml` to install utils with
```
notifications-utils = { git = "https://github.com/cds-snc/notifier-utils.git", branch = "show-part-of-sensitive-values"}
```
=> log last 2 characters of sensitive values

notifications_utils/clients/redis/bounce_rate.py, pyproject.toml, tests/test_bounce_rate.py
This PR adds a "seeding complete" flag for each service to Redis, so that we don't try to seed the data twice.
Also adds a `clear_bounce_rate_data` method to call before seeding the data.
See below for how these methods would be used:
- https://github.com/cds-snc/notification-api/pull/1834/files#diff-cca5917c620894fe770faa88835e9e186285d5b91a55fca992eb94d5dc87e635R823
- https://github.com/cds-snc/notification-api/pull/1834/files#diff-cca5917c620894fe770faa88835e9e186285d5b91a55fca992eb94d5dc87e635R850
=> Add seeding complete flag

notifications_utils/clients/redis/bounce_rate.py, pyproject.toml, tests/test_bounce_rate.py
Add a new method to check the current bounce status of a service. This method takes into account the minimum required 
volume of notifications threshold, only returning a status other than normal if the threshold is met.
Once merged, both `Admin` and `API` will need to be updated to call the client's `init_app` method during their initialization. API should be ready to go with [this PR](https://github.com/cds-snc/notification-api/pull/1837/commits/71189b59bf2302c7e5a19ce83a857de3b7325599) in that regard.
=> Add a minimum volume check when returning a service's bounce rate

.github/actions/waffles/requirements.txt, pyproject.toml
This release is to fix the waffles issue we're getting over here: 
PR: https://github.com/cds-snc/notification-api/pull/1837
CI failure: https://github.com/cds-snc/notification-api/actions/runs/4824377969/jobs/8594083380
=> New release 50.3.1

notifications_utils/clients/redis/redis_client.py
We can get Redis to count our sorted set directly with the [`ZCOUNT`](https://redis.io/commands/zcount/) function. This should provide better performance than returning all the data and counting it in python.
Tests should still pass in CI.
=> Use `ZCOUNT`

notifications_utils/clients/redis/bounce_rate.py, tests/test_bounce_rate.py
- To ensure there are no possibilities of system clock difference, use `utcnow()` when setting `_current_timestamp_ms`.
- `get_bounce_rate` now no longer rounds the result.
=> Use utcnow() instead of now(), remove rounding

notifications_utils/clients/redis/bounce_rate.py, tests/test_bounce_rate.py
This PR does 2 things:
- Switch timestamps from milliseconds to seconds - we don't need to use ms any more since we are using a `uuid` for our keys inside the sorted sets, and seconds will probably be less error prone
- add a function called `get_debug_data` that will pass some data to notification-api that we can log and may help us figure out our current bugs. This function should be removed later when we no longer need it.
=> Switch timestamps from milliseconds to seconds and add a fn for debugging

notifications_utils/url_safe_token.py, pyproject.toml, tests/test_url_safe_tokens.py
This is used by api to generate tokens for invitation emails.
We want to move towards using the salt "token" here rather the the DANGEROUS_SALT that api passes in. 
Tokens are used:
- in admin to verify email addresses ([valid for 1 hour](https://github.com/cds-snc/notification-admin/blob/main/app/config.py#L74))
- in api to invite people to teams ([valid for 2 days](https://github.com/cds-snc/notification-api/blob/main/app/config.py#L219))
Idea:
- currently the DANGEROUS_SALT is being used to generate and verify tokens
- in this PR we change the code to use "token" to generate and "token" and DANGEROUS_SALT to check (ie either one will work)
- after this code has been deployed in admin / api prod for 2 days, there will be no valid tokens signed with DANGEROUS_SALT
- we can then change …
=> Tweak token code

.github/actions/waffles/requirements.txt, notifications_utils/clients/redis/bounce_rate.py, pyproject.toml, tests/test_bounce_rate.py, tests/test_s3.py
This PR adds the `get_total_hard_bounces` method to our bounce rate client. This is so we can populate this number on the dashboard from Redis and will be used over in this PR: https://github.com/cds-snc/notification-admin/pull/1554
I also added `get_total_notifications` in case we need that later, and some docstrings.
Tests should pass in CI.
=> Add `get_total_hard_bounces` to the bounce rate client

notifications_utils/url_safe_token.py, pyproject.toml, tests/test_url_safe_tokens.py
Now that https://github.com/cds-snc/notification-admin/pull/1549 and https://github.com/cds-snc/notification-api/pull/1865 have merged we are not sending a salt argument to `generate_token()` nor to `check_token()`. This PR modifies those functions to not have a salt argument anymore.
Run admin and api locally, installing utils from this branch.
For all of these we just need to click on the link and verify that it goes to the appropriate Notify page without reporting that there is an error in the link.
=> Change token code to not have a salt argument

notifications_utils/__init__.py, notifications_utils/template.py, pyproject.toml, tests/test_template_types.py
This PR:
- introduces an email character limit of 50k to prevent extremely long emails from causing problems
- implements the limit both for templates with variables unpopulated (for use at template creation time) and for templates with variables populated (for use at send time)
-  adds a `CHAR_COUNT_LIMIT` property to `SMSMessageTemplate`, `EmailPreviewTemplate`, and `HTMLEmailTemplate` to reduce some of the `import` statements and extra logic we will need to implement in notification-api
- does not introduce any breaking changes
CI tests should pass. Manual testing will be easier when https://github.com/cds-snc/notification-api/pull/1896 is ready for review.
=> Add an email character limit

.github/actions/waffles/requirements.txt, pyproject.toml
I forgot to increment the waffles requirement when I tagged version 51.0.2. That is causing an error in the notification-api CI pipeline. This PR should fix that.
Tests should pass.
=> Bump to a new version 51.0.4

.github/actions/waffles/requirements.txt, pyproject.toml
This PR bumps utils version to 52.0.5 with added validation for template names.
=> bump utils version to 52.0.5

.github/actions/waffles/requirements.txt, pyproject.toml
Bumping version to include [dependency upgrades](https://github.com/cds-snc/notification-utils/pull/215) needed to completed the work on [1134](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1134)
=> bump utils version to 52.0.6

.github/actions/waffles/requirements.txt, notifications_utils/recipients.py, pyproject.toml, tests/test_logging.py
I made an incorrect assumption - that the first header was the required header for a template.
The assumption wasn't required previous to the changes I made for EN/ FR - I changed it back so that any column might have the required header for a template type
Tested this:
=> Fix assumption of required header being the first column

poetry.lock, pyproject.toml
This PR pins the transitive dependency `cryptography` to 41.0.2 to address mishandled SSH certificates found in older versions of the dependency. 
https://github.com/cds-snc/notification-utils/security/dependabot/21
=> Security/pin cryptography 41.0.2

.github/actions/waffles/requirements.txt, notifications_utils/clients/redis/redis_client.py, notifications_utils/decorators.py, pyproject.toml, tests/test_decorators.py, tests/test_redis_client.py
- Added a `decrby` method to the `redis_client`
- Added a simple decorator for functions that need to be behind a feature flag
[This API PR](https://github.com/cds-snc/notification-api/pull/2112) depends on these changes.
=> Add decrby to redis_client

pull_request_template.md
Adding a default PR template. There were none for this repository so it should be a welcomed
addition. The template follows latest agreed-upon format as discussed in the dev code review
session and reviewed by [latest PR here](https://github.com/cds-snc/notification-api/pull/2122).
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/304
None.
None.
=> Added default PR template

.github/actions/waffles/requirements.txt, notifications_utils/recipients.py, pyproject.toml, tests/test_recipient_validation.py
[Related issue 305](https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/305)
Fix a validation bug when the number is `None`. Also added a corresponding unit test.
Yes, this is an invalid number, but the [code that is crashing](https://github.com/cds-snc/notification-utils/blob/98bdc0d816e1f269011abec3f2209d743b6147a7/notifications_utils/recipients.py#L471-L481) contains the comment
> For use in places where you shouldn't error if the phone number is invalid - for example if firetext pass us
something in
Hence raising the error will produce a warning message and return the phone number return as-is, which might be `None` for the caller. The API would receive `None` upon calling this utility.
There are a few places in …
=> Fix validation bug when phone number in None

.github/actions/waffles/requirements.txt, notifications_utils/columns.py, notifications_utils/recipients.py, pyproject.toml, tests/test_recipient_csv.py
This PR adds validation to the `RecipientCSV` class to ensure that variables inserted do not exceed the 612 character limit, when sending SMS. A new property, `rows_with_combined_variable_content_too_long`, was added to check that the total message length does not exceed 612 when both the variable content and template content is combined.
=> Validate variables in CSV do not exceed daily limit

.github/actions/waffles/requirements.txt, notifications_utils/columns.py, pyproject.toml
The `recipient_error` property was falsely identifying certain row errors as `recipient_errors` and incorrectly marking rows as having recipient errors causing API to mis-interpret what error messages to return to the endpoint caller.
This PR addresses an issue that was blocking the release pipeline following bumps to Utils' version in API.
None.
=> Exclude content length errors from recipient_error prop

.github/actions/waffles/requirements.txt, notifications_utils/columns.py, pyproject.toml
Reverts cds-snc/notification-utils#290
We encountered a couple issues where SMS limit checking that was a part of this PR, and [#278](https://github.com/cds-snc/notification-utils/pull/278), was applying to bulk emails when it should only be applicable to bulk SMS.
=> Revert "Exclude content length errors from recipient_error prop"

.github/actions/waffles/requirements.txt, notifications_utils/columns.py, notifications_utils/recipients.py, pyproject.toml, tests/test_recipient_csv.py
Reverts [#278](https://github.com/cds-snc/notification-utils/pull/278)
We encountered a couple issues where SMS limit checking that was a part of this PR was applying to bulk emails when it should only be applicable to bulk SMS.
https://github.com/cds-snc/notification-utils/pull/292
https://github.com/cds-snc/notification-admin/pull/1822
https://github.com/cds-snc/notification-api/pull/2164
After this PR, https://github.com/cds-snc/notification-admin/pull/1822 and https://github.com/cds-snc/notification-api/pull/2164 are merged, we need to: 
1. Bump and tag utils.  
2. Bump the utils version in Admin and API.
> ⚠ If boxes cannot be checked off before merging the PR, they should be moved to the "Release Instructions" section with appropriate steps required to verify before release. For …
=> Revert PR #278 which added additional length checks to bulk SMS sends

.github/actions/waffles/requirements.txt, pyproject.toml
Bump waffles 
* https://github.com/cds-snc/notification-utils/pull/312
Tests pass
None.
=> Bump waffles version

notifications_utils/clients/redis/annual_limit.py, notifications_utils/clients/redis/redis_client.py, tests/test_annual_limit.py, tests/test_redis_client.py
This PR adds a new Redis client to facilitate tracking the current day's `delivered` and `failed` notification counts for a service. Two new hash keys were added, creating a data structure for each service:
Tracks `delivered` and `failed` email and sms notifications.
Tracks when warning and "limit reached" emails have been sent for a service.
* https://github.com/cds-snc/ADR/pull/14
_TODO: Fill in test instructions for the reviewer._
None.
=> Add Redis client for annual limits

.github/actions/waffles/requirements.txt, pyproject.toml
Bumping utils version to 52.3.6
* https://github.com/cds-snc/notification-utils/pull/330
_TODO: Fill in test instructions for the reviewer._
None.
=> Version 52.3.6

.github/actions/waffles/requirements.txt, notifications_utils/clients/redis/annual_limit.py, notifications_utils/clients/redis/redis_client.py, pyproject.toml, tests/test_annual_limit.py, tests/test_redis_client.py
This PR completes the annual limit Redis client.
- New base functionality available to all Redis clients to bulk update / delete Hash fields
- Fields can be manipulated via a list of keys or by using a key pattern
- Set and check the seeded_at values for notification counts
- Clear / reset daily notification counts
This will be called during `create_nightly_notification_status_for_day` to reset daily `failed` and `delivered` counts in Redis.
Tests pass & integrates with API.
None.
=> Annual Limit daily delivered & failed notification counts and seeding implementation

.github/actions/waffles/requirements.txt, notifications_utils/clients/redis/annual_limit.py, pyproject.toml, tests/test_annual_limit.py
This PR fixes an issue with the annual limit client. [Related alarm](https://gcdigital.slack.com/archives/C012W5K734Y/p1731530766936449?thread_ts=1731530661.925669&cid=C012W5K734Y) that caught this.
* https://github.com/cds-snc/notification-utils/pull/333
* https://github.com/cds-snc/notification-api/pull/2344
* 
Tests pass, issue in staging is resolved.
None.
=> Fix seeding bugs add missing tests

.github/actions/waffles/requirements.txt, notifications_utils/clients/redis/annual_limit.py, notifications_utils/clients/redis/redis_client.py, pyproject.toml, tests/test_annual_limit.py
This PR unifies the return types of all get methods so they return `None` if keys or fields are not found. It also improves method docstrings to clarify parameter data formats when using ambiguous data structures.
Tests pass, release, tag, and test integration in Admin and API.
None.
=> Unify all gets to return None if no values present in Redis

.github/actions/waffles/requirements.txt, notifications_utils/clients/redis/annual_limit.py, notifications_utils/clients/redis/redis_client.py, pyproject.toml, tests/test_annual_limit.py, tests/test_redis_client.py
A bug in `delete_hash_fields` caused it to consistently fail clearing all fields in a hash. The method optionally took in a mapping of fields to search for and delete. If the mapping was `None` it checked one of the hash keys to obtain the list of fields to delete. In the case of annual limits, there is no guarantee that all service's hashes in Redis will contain all possible fields (sms_delivered, sms_failed, email_delivered, email_failed).
- The fields mapping parameter is no longer optional 
Refactored annual limit client methods that returned numeric data to return 0 instead of None when no data was found in the queried hash e.g: `get_all_notification_counts()` used to return `None` if no fields were found in the hash, it now returns a dict with the expected fields initialized to 0: …
=> Fix bug in delete_hash_fields

.github/actions/waffles/requirements.txt, pyproject.toml
Python 3.12 doesn't include distutils anymore so we need to get it from somewhere else. [Setuptools is recommended](https://stackoverflow.com/questions/77233855/why-did-i-get-an-error-modulenotfounderror-no-module-named-distutils).
[Tested the action in the admin 3.12 branch](https://github.com/cds-snc/notification-admin/actions/runs/12128468332/job/33814890096?pr=1996). failed with waffles 53.0.0 but works with waffles from this branch.
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/464
Look at https://github.com/cds-snc/notification-admin/actions/runs/12128468332/job/33814890096?pr=1996
None.
> ⚠ If boxes cannot be checked off before merging the PR, they should be moved to the "Release Instructions" section …
=> add setuptools to waffles requirements.txt

notifications_utils/clients/redis/annual_limit.py, tests/test_annual_limit.py
This PR changes the annual limit client to skip the seeding of annual limit notification counts if there are no notifications to seed or their values are 0. This resolves an issue where `hmset` was called with an empty dict, causing the underlying pyRedis implementation to throw an exception.
* https://gcdigital.slack.com/archives/CNWA63606/p1736179889838109
Tests pass
None.
=> Skip notification seeding when nothing to seed

.github/actions/waffles/requirements.txt, notifications_utils/field.py, pyproject.toml, tests/test_template.py
This PR:
- adds a bunch of tests to check that, when a variable is in a link url, the html we get back is well formatted
- adds a 2nd regex pattern to match variables inside the url portion of a markdown link
- adds a regex replace to remove the double brackets from these variables, if no values are passed in and we are just previewing the html. This prevents the html from becoming incorrect after the markdown is converted to html
* https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/614
* https://github.com/cds-snc/notification-planning/issues/783
- open up notification-admin locally
- modify line 52 in pyproject.toml to read:
```
notifications-utils = { git = "https://github.com/cds-snc/notifier-utils.git", branch = …
```
=> Fix the preview formatting when a variable appears in a link url

.devcontainer/scripts/notify-dev-entrypoint.sh, .git-blame-ignore-revs
This PR adds [`.git-blame-ignore-revs`](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-and-understanding-files#ignore-commits-in-the-blame-view) to the project. This lets us to filter out specified commits when using git blame, e.g. bulk formatting and other changes that do not affect functionality.
To ignore a commit, just add the commit SHA to [.git-blame-ignore-revs](https://github.com/cds-snc/notification-utils/pull/351/files#diff-f247fbfbe928b907db42554d0b3006b28dd11c25a59be031abda73b11a2c934a)
1. Open `.git-blame-ignore-revs` and open one of the links to an ignored commit.
2. Open a file that the ignored commit changed and run git blame.
3. Note that the ignored commits are not present and the commit previous is shown instead.
=> Add .git-blame-ignore-revs

.github/actions/waffles/requirements.txt, notifications_utils/clients/redis/annual_limit.py, pyproject.toml, tests/test_annual_limit.py
Added year to date information in the annual limit client
```
notifications_v2: {
sms_delivered_today: int,
email_delivered_today: int,
sms_failed_today: int,
email_failed_today: int,
total_sms_fiscal_year_to_yesterday: int,
total_email_fiscal_year_to_yesterday: int,
}
```
Code is written to be backwards compatible
https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1767
_TODO: Fill in test instructions for the reviewer._
None.
=> Edit Annual Limit client to add new data around year info

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/scripts/notify-dev-entrypoint.sh
Similar to the work done in Admin and [API](https://github.com/cds-snc/notification-api/pull/2460) this PR makes our poetry dev container venv paths static so vscode consistently picks up and automatically uses the correct venv when switching between or rebuilding containers.
* https://github.com/cds-snc/notification-api/pull/2460
* https://github.com/cds-snc/notification-admin/pull/2076
1. In vscode - `ctrl + shift + p` and select `Python: clear workspace interpreter setting`
2. Rebuild the dev container 
3. Once the container is built, you may need to select the interpreter again
4. Open a new terminal / shell
5. Note that the virtual environment is automatically activated
1. Check out [this admin PR](https://github.com/cds-snc/notification-admin/pull/2076)
2. Rebuild the container …
=> Make poetry venv path static

.github/actions/waffles/requirements.txt, notifications_utils/clients/redis/annual_limit.py, pyproject.toml, tests/test_annual_limit.py
- Added some logging to help us catch when fields are missing in the annual_limit_notifications_v2 key
- Reworked backwards compatibility, previously the method expected ALL v2 keys to be present in order to update the seeded data.
- Set the seeding_at key only after the seeded data has been written to Redis, making the process more atomic in nature.
* https://gcdigital.slack.com/archives/CV38DBNVA/p1747062605779569?thread_ts=1747062585.422499&cid=CV38DBNVA
* CI is passing
* Once in staging, we need to verify that all services have their `total_email_fiscal_year_to_yesterday` keys populated correctly when a day rolls over.
> ⚠ If boxes cannot be checked off before merging the PR, they should be moved to the "Release Instructions" section with appropriate steps required to verify before …
=> Set seeding_at only after the seeded data exists in Redis

.github/actions/waffles/requirements.txt, notifications_utils/logging.py, pyproject.toml, tests/test_logging.py
Add `time_taken` to logging that  makes use of information already available in a flask request.  This will apply to logs in both admin and API.
* https://github.com/cds-snc/notification-planning/issues/1917
* Make a request in API
* Look at the log output
* Make a request in API
* Look at the log output
None.
=> feat(logging): add timing information to additional logging details

.github/actions/waffles/requirements.txt, notifications_utils/formatters.py, notifications_utils/template.py, pyproject.toml, tests/test_formatters.py
Nested list padding fix attempt 3. This PR adds a function to split the html into tokens. This makes the logic a bit easier to follow. 
1. Check out the api branch here: https://github.com/cds-snc/notification-api/compare/chore/update-utils-2?expand=1 and install with `poetry install`
2. run the app locally
3. send yourself a test message with a nested list, like this:
```
Bring with you:
* **Identification:**  -Add types of ID required or delete this bullet-
* **Documents:**  -List all documents needed and link to them if possible-
* [-document 1-](https://link1.ca)
* [-document 2-](https://link2.ca)
* **Other:** Add more bullets with other items or delete this bullet-
```
4. verify that you don't see the extra padding in the email
None.
> ⚠ If boxes cannot be checked off before merging …
=> Fix nested list padding attempt 3
